using Econometrics, StatsPlots, MCMCChains, DelimitedFiles
chain = readdlm("chain")
chn = Chains(chain)
display(chn)
plot(chn)
savefig("chain.png")
p = npdensity(chain[:,1])
plot!(legend=false)
savefig(p, "mu.png")
p = npdensity(chain[:,2])
plot!(legend=false)
savefig(p, "kappa.png")
p = npdensity(chain[:,3])
plot!(legend=false)
savefig(p, "alpha.png")
p = npdensity(chain[:,4])
plot!(legend=false)
savefig(p, "sigma.png")
p = npdensity(chain[:,5])
plot!(legend=false)
savefig(p, "rho.png")
p = npdensity(chain[:,6])
plot!(legend=false)
savefig(p, "lambda0.png")
p = npdensity(chain[:,7])
plot!(legend=false)
savefig(p, "lambda1.png")
p = npdensity(chain[:,8])
plot!(legend=false)
savefig(p, "tau.png")



