using Pkg
Pkg.activate("../../../")
using DelimitedFiles
using Plots
chain = readdlm("chain")
p = npdensity(chain[:,1])
plot!(p, legend=false)
savefig( "mu.svg")
p = npdensity(chain[:,2])
plot!(p, legend=false)
savefig( "kappa.svg")
p = npdensity(chain[:,3])
plot!(p, legend=false)
savefig( "alpha.svg")
p = npdensity(chain[:,4])
plot!(p, legend=false)
savefig( "sigma.svg")
p = npdensity(chain[:,5])
plot!(p, legend=false)
savefig( "rho.svg")
p = npdensity(chain[:,6])
plot!(p, legend=false)
savefig( "lambda0.svg")
p = npdensity(chain[:,7])
plot!(p, legend=false)
savefig( "lambda1.svg")
p = npdensity(chain[:,8])
plot!(p, legend=false)
savefig( "tau.svg")
